# Can't use the {::8} notation to get a short sha in the variables section, so exporting below
# Also the CI_REGISTRY variable is set incorrectly in GitLab - so exporting to correct value
before_script:
  - export CI_COMMIT_SHA_SHORT=${CI_COMMIT_SHA::8}
  - export CI_REGISTRY=dockerhub.ebi.ac.uk
  - export IMAGE_NAME=$CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA_SHORT

stages:
  - build
  - deploy_dev
  - deploy_prod

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_NAME

# Reusable template, requires the $KUBE_CONFIG and $NAMESPACE variables to be set
# This subsitutes the environment variable $IMAGE_NAME in the overlay file, and deploys
.template: &deploy
  image: ebiwd/alpine-ssh:latest
  script:
    - mkdir -p $HOME/.kube
    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - envsubst '$IMAGE_NAME' < k8s/overlays/caas/ci_image.yaml > file.tmp && mv file.tmp k8s/overlays/caas/ci_image.yaml
    - kubectl kustomize k8s/overlays/caas/ | kubectl --namespace=$NAMESPACE apply -f -

deploy_to_hh_dev:
  stage: deploy_dev
  variables:
    NAMESPACE: static-sites-dev
    KUBE_CONFIG: $HH_KUBE_CONFIG
  <<: *deploy

deploy_to_hx_dev:
  stage: deploy_dev
  variables:
    NAMESPACE: static-sites-dev
    KUBE_CONFIG: $HX_KUBE_CONFIG
  <<: *deploy

deploy_to_hh_prod:
  stage: deploy_prod
  only:
    - tags
  except:
    - branches
  variables:
    NAMESPACE: static-sites-prod
    KUBE_CONFIG: $HH_KUBE_CONFIG
  <<: *deploy

deploy_to_hx_prod:
  stage: deploy_prod
  only:
    - tags
  except:
    - branches
  variables:
    NAMESPACE: static-sites-prod
    KUBE_CONFIG: $HX_KUBE_CONFIG
  <<: *deploy
